// <auto-generated />
using System;
using GestionGastos.Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionGastos.Api.Migrations
{
    [DbContext(typeof(GestionGastosDbContext))]
    [Migration("20260824005000_UnicaMonedaPredeterminada")]
    partial class UnicaMonedaPredeterminada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionGastos.Api.Dominio.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasDefaultValue(1ul)
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<sbyte>("Tipo")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nombre", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ux_categoria_ambito_nombre_tipo");

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = 1ul,
                            Nombre = "Comida",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 2,
                            Activa = 1ul,
                            Nombre = "Transporte",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 3,
                            Activa = 1ul,
                            Nombre = "Vivienda",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 4,
                            Activa = 1ul,
                            Nombre = "Servicios",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 5,
                            Activa = 1ul,
                            Nombre = "Salud",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 6,
                            Activa = 1ul,
                            Nombre = "Ocio",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 7,
                            Activa = 1ul,
                            Nombre = "Otros",
                            Tipo = (sbyte)0
                        },
                        new
                        {
                            Id = 8,
                            Activa = 1ul,
                            Nombre = "Sueldo",
                            Tipo = (sbyte)1
                        },
                        new
                        {
                            Id = 9,
                            Activa = 1ul,
                            Nombre = "Ingreso extra",
                            Tipo = (sbyte)1
                        },
                        new
                        {
                            Id = 10,
                            Activa = 1ul,
                            Nombre = "Otros",
                            Tipo = (sbyte)1
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Dominio.Moneda", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("codigo");

                    b.Property<byte>("Decimales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)2)
                        .HasColumnName("decimales");

                    b.Property<ulong>("EsPredeterminada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit(1)")
                        .HasDefaultValue(0ul)
                        .HasColumnName("es_predeterminada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("simbolo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("moneda", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "ARS",
                            Decimales = (byte)2,
                            EsPredeterminada = 1ul,
                            Nombre = "Peso argentino",
                            Simbolo = "$"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "USD",
                            Decimales = (byte)2,
                            EsPredeterminada = 0ul,
                            Nombre = "Dólar estadounidense",
                            Simbolo = "US$"
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Dominio.Movimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<short>("MonedaId")
                        .HasColumnType("smallint")
                        .HasColumnName("moneda_id");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(11,2)")
                        .HasColumnName("monto");

                    b.Property<sbyte>("Tipo")
                        .HasColumnType("tinyint")
                        .HasColumnName("tipo");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("UsuarioId", "Fecha", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_movimiento_usuario_fecha");

                    b.ToTable("movimiento", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_monto_positivo", "monto > 0");
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Dominio.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "semilla@gestiongastos.local"
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Dominio.Categoria", b =>
                {
                    b.HasOne("GestionGastos.Api.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GestionGastos.Api.Dominio.Movimiento", b =>
                {
                    b.HasOne("GestionGastos.Api.Dominio.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionGastos.Api.Dominio.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionGastos.Api.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Moneda");
                });
#pragma warning restore 612, 618
        }
    }
}
